on:
  push:
    branches:
      - main
      - dev
      - stage

env:
  test: hello
  branch: ${{ github.head_ref || github.ref_name }}
  parameter_key: /${{ vars.MY_NAME }}/$branch # kevin/(main|dev|stage)
  group_name: test
  zip_name: test-$branch-shell.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # echo ${ branch } not worked
      # echo ${{ branch }} not worked

      - name: Echo test
        run: |
          echo $branch
          echo $parameter_key

      - name: Re-define group_name 1
        if: ${{ env.branch == 'main' }}
        run: |
          echo "group_name=main-branch" >> $GITHUB_ENV

      - name: Re-define group_name 2
        if: ${{ env.branch != 'main' }}
        run: |
          echo 'group_name=${{ env.branch }} | sed 's/.*\///'' >> $GITHUB_ENV
          echo ${{ env.group_name }}
