on:
  push:
    branches:
      - main
      - dev
      - stage

env:
  test: hello
  branch: ${{ github.head_ref || github.ref_name }}
  parameter_key: /${{ vars.MY_NAME }}/$branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x ./scripts/log.sh
          ./scripts/log.sh $branch
        shell: bash

      - name: Echo test
        run: |
          echo "Test1: " $test
          echo "Test2: " ${test}
          echo "Test3: " ${{test}}
          echo "Test4: $test"
          echo "Test5: ${test}"
          echo "Test6: ${{test}}"

      - name: Echo env variables
        run: |
          echo "Current branch: ${{ env.branch }}"
          echo "Parameter key: ${{ env.parameter_key }}"

      - name: Commit and push
        run: |
          git add .
          git config --global user.email "maketheworldwise@squares.ai"
          git config --global user.name "sqs-maketheworldwise"
          git commit -am "log"
          git push
