on:
  push:
    branches:
      - main
      - dev
      - stage

env:
  branch: ${{ github.head_ref || github.ref_name }}
  parameter_key: /kevin/$branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x ./scripts/log.sh
          ./scripts/log.sh $branch
        shell: bash

      - name: Echo
        run: |
          echo "Current branch: ${{env.branch}}"
          echo "Parameter key: ${{env.parameter_key}}"

      - name: Commit and push
        run: |
          git add .
          git config --global user.email "maketheworldwise@squares.ai"
          git config --global user.name "sqs-maketheworldwise"
          git commit -am "log"
          git push
