on:
  push:
    branches:
      - main
      - dev
      - stage
      - feat/test
  pull_request:
    branches:
      - main
      - stg
      - dev

env:
  test: feat/tttt
  branch: ${{ github.head_ref || github.ref_name }}
  parameter_key: /${{ vars.MY_NAME }}/$branch # kevin/(main|dev|stage)
  group_name: test
  zip_name: test-$branch-shell.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # echo ${ branch } not worked
      # echo ${{ branch }} not worked
      - name: Echo test
        run: |
          echo $branch
          echo $parameter_key

      - name: Re-define group_name 1
        if: ${{ env.branch == 'main' }}
        run: |
          echo "group_name=prod" >> $GITHUB_ENV

      - name: Re-define group_name 2
        run: |
          echo "testing=$(echo ${{ env.test }} | sed 's/.*\///' )" >> $GITHUB_ENV

      - name: test
        if: ${{ github.event_name != 'push' && github.event_name == 'pull_request' && github.event.pull_request.merged != 'true'}}
        run: |
          echo ${{ env.testing }}
